export const chatMessages = [
    "Hello everyone!",
    "This is awesome 🔥",
    "Where are you watching from?",
    "Like and subscribe!",
    "Can someone explain what's going on?",
    "Shoutout to the host!",
    "Love this stream!",
    "This song hits different 🎵",
    "Keep it up!",
    "LMAO 😂",
    "Waiting for the drop!",
    "This chat is wild lol",
    "Please read my comment 🙏",
    "Nice gameplay!",
    "How long is the stream?",
    "Who's here from India?",
    "Such a vibe!",
    "I was here before 1M views 😎",
    "Notifications squad! 🔔",
    "Can mods help?",
    "Replay gang ✌️",
    "Best livestream ever!",
    "What did I miss?",
    "Yessss!",
    "No way that just happened!",
    "This part is crazy!",
    "🔥🔥🔥",
    "Let's gooo!",
    "Who's your favorite?",
    "Chat is so fast!",
    "Legendary moment right here.",
    "Subbed just now!",
    "Nice camera setup!",
    "Anyone else watching in 1080p?",
    "When is the next stream?",
    "OMG 😱",
    "Clutch move!",
    "I'm dying laughing 😂",
    "Where are the mods?",
    "This deserves more views!",
    "Happy to be here 💯",
    "First time in live chat!",
    "Spam W in the chat!",
    "Don’t forget to like!",
    "Big fan from Brazil 🇧🇷",
    "Yo this is intense!",
    "BRB, getting snacks 🍿",
    "Streaming goals!",
    "Facts 👏",
    "No cap!",
];

export const userNames = [
    "AlphaWolf99", "GamerGirl23", "Sunny_Day", "NightHawk", "CodeMaster", "MusicLover", "EpicFail123",
    "ChocoBunny", "PixelPenguin", "QuantumCoder", "SkyWalker42", "Legend27", "BingeWatcher",
    "CoolKid", "DramaQueen", "MemeMachine", "NoScopeNinja", "LofiGuy", "KPopAddict", "Techie101",
    "JustVibin", "SleepySloth", "RiderX", "GlitchQueen", "FunTimeFox", "SilentWatcher", "DarkKnight",
    "ZoomBoom", "CrimsonTide", "OceanEyes", "HappyFeet", "Speedster22", "EmojiFan", "PandaExpress",
    "Marshmellow", "ToxicBanana", "InfiniteLoop", "FireFly", "CuteCactus", "AlienZ", "ShadowFox",
    "LOLManiac", "DataLord", "CookieMonster", "SneakyPanda", "IceDragon", "SassyPotato", "FlexGuru",
    "FuzzyWuzzy", "WittyKitty", "BanHammer", "RebelSoul", "SmartDonkey", "GroovyTomato", "NeonLights",
    "WaffleKing", "SleepDeprived", "BubblyBear", "BlazeStorm", "VanillaTwist", "ZebraDance",
    "ThunderBolt", "SnorlaxFan", "BeastMode", "MagicUnicorn", "DinoNuggets", "CyberFreak", "TrollHunter",
    "CaptainCrunch", "KingOfNothing", "NightOwl", "BananaBread", "SonicBoom", "FriendlyGhost",
    "PixelRacer", "RickRoller", "Meowster", "NachoKing", "CloudSurfer", "ViralGenie", "ToxicKitten",
    "LunaStar", "MonkeyBusiness", "UltraGamer", "LazyKoala", "TheRealDeal", "MoonWalker", "ChillVibes",
    "PenguinDance", "RetroDude", "XtremeCoder", "SpicyTuna", "JellyBean", "BugSlayer", "RainbowDash",
    "GameChanger", "TheGlitch", "SaltyPickle", "Starlord", "NyanCat", "NovaCore", "PixelatedMind",
    "TurtleTamer", "VapeLord", "WhaleWhisperer", "SoftBreeze", "ZestyLemon", "ComicNerd", "HackerBoi",
    "FluffyPenguin", "SnappySnail", "GhostMode", "CrazyCoconut", "CheesyPasta", "BrightSide", "BloopFish",
    "DoodleBug", "WittyBanana", "TacoKnight", "L33tHax0r", "DonutQueen", "TheWatcher", "SparkleMage",
    "MrBeastClone", "BuzzKill", "ThatOneGuy", "AnimeAddict", "CoffeeLover", "DramaAlertFan"
]

export const chats = [
    { name: "AlphaWolf99", msg: "Hello everyone!" },
    { name: "GamerGirl23", msg: "This is awesome 🔥" },
    { name: "Sunny_Day", msg: "Where are you watching from?" },
    { name: "NightHawk", msg: "Like and subscribe!" },
    { name: "CodeMaster", msg: "Can someone explain what's going on?" },
    { name: "MusicLover", msg: "Shoutout to the host!" },
    { name: "EpicFail123", msg: "Love this stream!" },
    { name: "ChocoBunny", msg: "This song hits different 🎵" },
    { name: "PixelPenguin", msg: "Keep it up!" },
    { name: "QuantumCoder", msg: "LMAO 😂" },
    { name: "SkyWalker42", msg: "Waiting for the drop!" },
    { name: "Legend27", msg: "This chat is wild lol" },
    { name: "CoolKid", msg: "Please read my comment 🙏" },
    { name: "DramaQueen", msg: "Nice gameplay!" },
    { name: "MemeMachine", msg: "How long is the stream?" },
    { name: "NoScopeNinja", msg: "Who's here from India?" },
    { name: "LofiGuy", msg: "Such a vibe!" },
    { name: "KPopAddict", msg: "I was here before 1M views 😎" },
    { name: "Techie101", msg: "Notifications squad! 🔔" },
    { name: "JustVibin", msg: "Can mods help?" },
    { name: "SleepySloth", msg: "Replay gang ✌️" },
    { name: "RiderX", msg: "Best livestream ever!" },
    { name: "GlitchQueen", msg: "What did I miss?" },
    { name: "FunTimeFox", msg: "Yessss!" },
    { name: "SilentWatcher", msg: "No way that just happened!" },
    { name: "DarkKnight", msg: "This part is crazy!" },
    { name: "ZoomBoom", msg: "🔥🔥🔥" },
    { name: "CrimsonTide", msg: "Let's gooo!" },
    { name: "OceanEyes", msg: "Who's your favorite?" },
    { name: "HappyFeet", msg: "Chat is so fast!" },
    { name: "Speedster22", msg: "Legendary moment right here." },
    { name: "EmojiFan", msg: "Subbed just now!" },
    { name: "PandaExpress", msg: "Nice camera setup!" },
    { name: "Marshmellow", msg: "Anyone else watching in 1080p?" },
    { name: "ToxicBanana", msg: "When is the next stream?" },
    { name: "InfiniteLoop", msg: "OMG 😱" },
    { name: "FireFly", msg: "Clutch move!" },
    { name: "CuteCactus", msg: "I'm dying laughing 😂" },
    { name: "AlienZ", msg: "Where are the mods?" },
    { name: "ShadowFox", msg: "This deserves more views!" },
    { name: "LOLManiac", msg: "Happy to be here 💯" },
    { name: "DataLord", msg: "First time in live chat!" },
    { name: "CookieMonster", msg: "Spam W in the chat!" },
    { name: "SneakyPanda", msg: "Don’t forget to like!" },
    { name: "IceDragon", msg: "Big fan from Brazil 🇧🇷" },
    { name: "SassyPotato", msg: "Yo this is intense!" },
    { name: "FlexGuru", msg: "BRB, getting snacks 🍿" },
    { name: "FuzzyWuzzy", msg: "Streaming goals!" },
    { name: "WittyKitty", msg: "Facts 👏" },
    { name: "BanHammer", msg: "No cap!" },
    { name: "RebelSoul", msg: "Hello everyone!" },
    { name: "SmartDonkey", msg: "This is awesome 🔥" },
    { name: "GroovyTomato", msg: "Where are you watching from?" },
    { name: "NeonLights", msg: "Like and subscribe!" },
    { name: "WaffleKing", msg: "Can someone explain what's going on?" },
    { name: "SleepDeprived", msg: "Shoutout to the host!" },
    { name: "BubblyBear", msg: "Love this stream!" },
    { name: "BlazeStorm", msg: "This song hits different 🎵" },
    { name: "VanillaTwist", msg: "Keep it up!" },
    { name: "ZebraDance", msg: "LMAO 😂" },
    { name: "ThunderBolt", msg: "Waiting for the drop!" },
    { name: "SnorlaxFan", msg: "This chat is wild lol" },
    { name: "BeastMode", msg: "Please read my comment 🙏" },
    { name: "MagicUnicorn", msg: "Nice gameplay!" },
    { name: "DinoNuggets", msg: "How long is the stream?" },
    { name: "CyberFreak", msg: "Who's here from India?" },
    { name: "TrollHunter", msg: "Such a vibe!" },
    { name: "CaptainCrunch", msg: "I was here before 1M views 😎" },
    { name: "KingOfNothing", msg: "Notifications squad! 🔔" },
    { name: "NightOwl", msg: "Can mods help?" },
    { name: "BananaBread", msg: "Replay gang ✌️" },
    { name: "SonicBoom", msg: "Best livestream ever!" },
    { name: "FriendlyGhost", msg: "What did I miss?" },
    { name: "PixelRacer", msg: "Yessss!" },
    { name: "RickRoller", msg: "No way that just happened!" },
    { name: "Meowster", msg: "This part is crazy!" },
    { name: "NachoKing", msg: "🔥🔥🔥" },
    { name: "CloudSurfer", msg: "Let's gooo!" },
    { name: "ViralGenie", msg: "Who's your favorite?" },
    { name: "ToxicKitten", msg: "Chat is so fast!" },
    { name: "LunaStar", msg: "Legendary moment right here." },
    { name: "MonkeyBusiness", msg: "Subbed just now!" },
    { name: "UltraGamer", msg: "Nice camera setup!" },
    { name: "LazyKoala", msg: "Anyone else watching in 1080p?" },
    { name: "TheRealDeal", msg: "When is the next stream?" },
    { name: "MoonWalker", msg: "OMG 😱" },
    { name: "ChillVibes", msg: "Clutch move!" },
    { name: "PenguinDance", msg: "I'm dying laughing 😂" },
    { name: "RetroDude", msg: "Where are the mods?" },
    { name: "XtremeCoder", msg: "This deserves more views!" },
    { name: "SpicyTuna", msg: "Happy to be here 💯" },
    { name: "JellyBean", msg: "First time in live chat!" },
    { name: "BugSlayer", msg: "Spam W in the chat!" },
    { name: "RainbowDash", msg: "Don’t forget to like!" },
    { name: "GameChanger", msg: "Big fan from Brazil 🇧🇷" },
    { name: "TheGlitch", msg: "Yo this is intense!" },
    { name: "SaltyPickle", msg: "BRB, getting snacks 🍿" },
    { name: "Starlord", msg: "Streaming goals!" },
    { name: "NyanCat", msg: "Facts 👏" },
    { name: "NovaCore", msg: "No cap!" },
    { name: "PixelatedMind", msg: "Hello everyone!" },
    { name: "TurtleTamer", msg: "This is awesome 🔥" },
    { name: "VapeLord", msg: "Where are you watching from?" },
    { name: "WhaleWhisperer", msg: "Like and subscribe!" },
    { name: "SoftBreeze", msg: "Can someone explain what's going on?" },
    { name: "ZestyLemon", msg: "Shoutout to the host!" },
    { name: "ComicNerd", msg: "Love this stream!" },
    { name: "HackerBoi", msg: "This song hits different 🎵" },
    { name: "FluffyPenguin", msg: "Keep it up!" },
    { name: "SnappySnail", msg: "LMAO 😂" },
    { name: "GhostMode", msg: "Waiting for the drop!" },
    { name: "CrazyCoconut", msg: "This chat is wild lol" },
    { name: "CheesyPasta", msg: "Please read my comment 🙏" },
    { name: "BrightSide", msg: "Nice gameplay!" },
    { name: "BloopFish", msg: "How long is the stream?" },
    { name: "DoodleBug", msg: "Who's here from India?" },
    { name: "WittyBanana", msg: "Such a vibe!" },
    { name: "TacoKnight", msg: "I was here before 1M views 😎" },
    { name: "L33tHax0r", msg: "Notifications squad! 🔔" },
    { name: "DonutQueen", msg: "Can mods help?" },
    { name: "TheWatcher", msg: "Replay gang ✌️" },
    { name: "SparkleMage", msg: "Best livestream ever!" },
    { name: "MrBeastClone", msg: "What did I miss?" },
    { name: "BuzzKill", msg: "Yessss!" },
    { name: "ThatOneGuy", msg: "No way that just happened!" },
    { name: "AnimeAddict", msg: "This part is crazy!" },
    { name: "CoffeeLover", msg: "🔥🔥🔥" },
    { name: "DramaAlertFan", msg: "Let's gooo!" },
    { name: "TwerkSaurus", msg: "Who's your favorite?" },
    { name: "CodeWizard", msg: "Chat is so fast!" },
    { name: "SpaceCadet", msg: "Legendary moment right here." },
    { name: "BruhMoment", msg: "Subbed just now!" },
    { name: "SaucyPineapple", msg: "Nice camera setup!" },
    { name: "DramaDuck", msg: "Anyone else watching in 1080p?" },
    { name: "ToxicFish", msg: "When is the next stream?" },
    { name: "LazyGenius", msg: "OMG 😱" },
    { name: "Firecracker", msg: "Clutch move!" },
    { name: "EmojiStorm", msg: "I'm dying laughing 😂" },
    { name: "ShrimpDaddy", msg: "Where are the mods?" },
    { name: "SilentEcho", msg: "This deserves more views!" },
    { name: "CerealKiller", msg: "Happy to be here 💯" },
    { name: "OreoFan", msg: "First time in live chat!" },
    { name: "TheSimp", msg: "Spam W in the chat!" },
    { name: "MrRandom", msg: "Don’t forget to like!" }
  ];
  
export function filterShorts(videos) {
    if (videos) {
      const filter =  videos.filter((video) => {
          return !video.snippet.description.toLowerCase().includes("#shorts");
      })
     return filter;
    }
}